name: CI

on:
  push:
    branches:
      - 'feat/**'
      - 'ci/**'
      - 'issue/**'
      - 'master'
      - 'develop'
      - 'hotfix/**'
      - 'bug/**'
      - 'fix/**'
      - 'refactor/**'
      - 'build/**'
      - 'test/**'
      - 'dependabot/**'
    tags:
      - '*'

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.8.6
          architecture: x64
      - name: Get notes
        id: generate_notes
        uses: anmarkoulis/commitizen-changelog-reader@develop
        with:
          tag_name: refs/tags/v1.0.0
          changelog: CHANGELOG.md
