on:
  workflow_call:
    inputs:
      upload_docs:
        description: Upload documentation to read the docs
        required: false
        default: false
        type: boolean
    secrets:
      RTDS_WEBHOOK_TOKEN:
        required: false
      RTDS_WEBHOOK_URL:
        required: false

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          architecture: x64
      - name: Checkout Repository
        uses: actions/checkout@main
      - name: Run sphinx build
        run: make build-sphinx
      - name: Upload documentation as artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/_build/html
      - name: Upload to read the docs
        if: ${{ inputs.upload_docs == 'true' || inputs.upload_docs == true }}
        run: curl -X POST -d "branches=${{ github.ref_name }}" -d "token=${{ secrets.RTDS_WEBHOOK_TOKEN }}"  ${{ secrets.RTDS_WEBHOOK_URL }}
