name: CI

on:
  pull_request:
    branches:
      - "main"

jobs:
  precommit:
    uses: ./.github/workflows/precommit.yml

  unittest:
    uses: ./.github/workflows/test.yml

  documentation:
    uses: ./.github/workflows/docs.yml
    with:
      upload_docs: false
