on:
  workflow_call:

jobs:
  precommit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ "3.8", "3.9", "3.10", "3.11" ]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run precommit
        run: make pre-commit args=--all-files
