name: Tag

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: tag
  cancel-in-progress: true

jobs:
  release:
    uses: ./.github/workflows/release.yml
    secrets:
      pypi_password: ${{ secrets.pypi_password }}

  docs:
    uses: ./.github/workflows/docs.yml
    with:
      upload_docs: true
    secrets:
      RTDS_WEBHOOK_TOKEN: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
      RTDS_WEBHOOK_URL: ${{ secrets.RTDS_WEBHOOK_URL }}
